SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM
  PATIENT
  JOIN APPOINTMENT AS A USING (PT_NO)
  JOIN DOCTOR ON MDDR_ID = DR_ID
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;
