SELECT
  REST_ID,
  REST_NAME,
  FOOD_TYPE,
  FAVORITES,
  ADDRESS,
  ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM
  REST_INFO
  JOIN REST_REVIEW USING (REST_ID)
GROUP BY REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;
