SELECT
  CAR_ID,
  CAR_TYPE,
  FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM
  CAR_RENTAL_COMPANY_CAR
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
WHERE
  CAR_TYPE IN ('세단', 'SUV')
  AND CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
  )
  AND DURATION_TYPE = '30일 이상'
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
